export enum DocumentType {
  IDENTITE = 'IDENTITE',
  JUSTIFICATIF_DOMICILE = 'JUSTIFICATIF_DOMICILE',
  JUSTIFICATIF_REVENU = 'JUSTIFICATIF_REVENU',
  PROSPECTUS = 'PROSPECTUS',
  RAPPORT_FINANCIER = 'RAPPORT_FINANCIER',
  CONTRAT_SOUSCRIPTION = 'CONTRAT_SOUSCRIPTION',
  BULLETIN_SOUSCRIPTION = 'BULLETIN_SOUSCRIPTION',
  STATUTS_SPV = 'STATUTS_SPV',
  KBIS = 'KBIS',
  PERMIS_CONSTRUIRE = 'PERMIS_CONSTRUIRE',
  PHOTO_PROJET = 'PHOTO_PROJET',
  AUTRE = 'AUTRE',
}

export enum DocumentRelatedTo {
  USER = 'USER',
  PROJECT = 'PROJECT',
  INVESTMENT = 'INVESTMENT',
}
