services:
  db:
    image: postgres
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}

  redis:
    image: redis
    ports:
      - '6379:6379'
