import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1780895612145 implements MigrationInterface {
    name = 'InitSchema1780895612145'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT "FK_992bc479833a12a0f2bfeb29371"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT "FK_42a7f009e9f4e9eba6cc349dc4d"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT "FK_a721586d3aad982a449d4d6dec4"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT "FK_a7552c678d79fc7a7256ee05bf1"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "latitude"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "longitude"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "nbFractions"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "prixFraction"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "previsionnel"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "chronologie"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "garanties"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "echeancierEmprunteur"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "annuleLe"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "adresseComplete"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "youtubeUrl"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "motifAnnulation"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN "prelevementIR"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN "prelevementCSG"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN "rappelJ7Envoye"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN "rappelJ1Envoye"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP COLUMN "nbFractions"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "patrimoineDeclare"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "montantMaxConseille"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "dernierContactAdmin"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "prochainContactDu"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "niveauRisque"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "lu"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "titre"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD "projet_id" uuid`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD "utilisateur_id" integer`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD "investissement_id" uuid`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD "vendeur_id" integer`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "adresseComplete" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "latitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "longitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "youtubeUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "nbFractions" integer`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "prixFraction" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "previsionnel" jsonb`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "chronologie" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "garanties" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "echeancierEmprunteur" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "motifAnnulation" text`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "annuleLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD "prelevementIR" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD "prelevementCSG" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD "rappelJ7Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD "rappelJ1Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD "nbFractions" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "prenom" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "nom" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "nomNaissance" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "paysNaissance" character(2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "patrimoineDeclare" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "montantMaxConseille" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "niveauRisque" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "dernierContactAdmin" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "prochainContactDu" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "type" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "titre" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "message" text`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "lu" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ALTER COLUMN "dateNaissance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD CONSTRAINT "FK_791283f3f6f2453b189909660a6" FOREIGN KEY ("projet_id") REFERENCES "projet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD CONSTRAINT "FK_2a87c12126792ee18fac7b2e8d8" FOREIGN KEY ("utilisateur_id") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD CONSTRAINT "FK_a17851bfda0918cbfb0d698490a" FOREIGN KEY ("investissement_id") REFERENCES "investissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD CONSTRAINT "FK_82548d1f8467830e7ec10fcd0d2" FOREIGN KEY ("vendeur_id") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD CONSTRAINT "FK_992bc479833a12a0f2bfeb29371" FOREIGN KEY ("projetId") REFERENCES "projet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD CONSTRAINT "FK_42a7f009e9f4e9eba6cc349dc4d" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD CONSTRAINT "FK_a721586d3aad982a449d4d6dec4" FOREIGN KEY ("investissementId") REFERENCES "investissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD CONSTRAINT "FK_a7552c678d79fc7a7256ee05bf1" FOREIGN KEY ("vendeurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT "FK_a7552c678d79fc7a7256ee05bf1"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT "FK_a721586d3aad982a449d4d6dec4"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT "FK_42a7f009e9f4e9eba6cc349dc4d"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT "FK_992bc479833a12a0f2bfeb29371"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT "FK_82548d1f8467830e7ec10fcd0d2"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT "FK_a17851bfda0918cbfb0d698490a"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT "FK_2a87c12126792ee18fac7b2e8d8"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT "FK_791283f3f6f2453b189909660a6"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ALTER COLUMN "dateNaissance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "lu"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "titre"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "prochainContactDu"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "dernierContactAdmin"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "niveauRisque"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "montantMaxConseille"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "patrimoineDeclare"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "paysNaissance"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "nomNaissance"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "nom"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN "prenom"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP COLUMN "nbFractions"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN "rappelJ1Envoye"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN "rappelJ7Envoye"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN "prelevementCSG"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN "prelevementIR"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "annuleLe"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "motifAnnulation"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "echeancierEmprunteur"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "garanties"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "chronologie"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "previsionnel"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "prixFraction"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "nbFractions"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "youtubeUrl"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "longitude"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "latitude"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN "adresseComplete"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP COLUMN "vendeur_id"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP COLUMN "investissement_id"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP COLUMN "utilisateur_id"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP COLUMN "projet_id"`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "message" text`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "titre" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "type" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "lu" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "niveauRisque" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "prochainContactDu" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "dernierContactAdmin" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "montantMaxConseille" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD "patrimoineDeclare" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD "nbFractions" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD "rappelJ1Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD "rappelJ7Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD "prelevementCSG" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD "prelevementIR" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "motifAnnulation" text`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "youtubeUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "adresseComplete" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "annuleLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "echeancierEmprunteur" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "garanties" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "chronologie" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "previsionnel" jsonb`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "prixFraction" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "nbFractions" integer`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "longitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD "latitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD CONSTRAINT "FK_a7552c678d79fc7a7256ee05bf1" FOREIGN KEY ("vendeurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD CONSTRAINT "FK_a721586d3aad982a449d4d6dec4" FOREIGN KEY ("investissementId") REFERENCES "investissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD CONSTRAINT "FK_42a7f009e9f4e9eba6cc349dc4d" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD CONSTRAINT "FK_992bc479833a12a0f2bfeb29371" FOREIGN KEY ("projetId") REFERENCES "projet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
