import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1780899617108 implements MigrationInterface {
    name = 'InitSchema1780899617108'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_992bc479833a12a0f2bfeb29371"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_42a7f009e9f4e9eba6cc349dc4d"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a721586d3aad982a449d4d6dec4"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a7552c678d79fc7a7256ee05bf1"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "prixFraction"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "echeancierEmprunteur"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "longitude"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "adresseComplete"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "latitude"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "garanties"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "previsionnel"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "youtubeUrl"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "chronologie"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "nbFractions"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "annuleLe"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "motifAnnulation"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN IF EXISTS "prelevementIR"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN IF EXISTS "prelevementCSG"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN IF EXISTS "rappelJ7Envoye"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN IF EXISTS "rappelJ1Envoye"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP COLUMN IF EXISTS "nbFractions"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "prochainContactDu"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "dernierContactAdmin"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "montantMaxConseille"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "niveauRisque"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "patrimoineDeclare"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "lu"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "type"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "message"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "titre"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "createdAt"`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "adresseComplete" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "latitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "longitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "youtubeUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "nbFractions" integer`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "prixFraction" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "previsionnel" jsonb`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "chronologie" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "garanties" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "echeancierEmprunteur" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "motifAnnulation" text`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "annuleLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "prelevementIR" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "prelevementCSG" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "rappelJ7Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "rappelJ1Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "nbFractions" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "projet_id" uuid`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "utilisateur_id" integer`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "investissement_id" uuid`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "vendeur_id" integer`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "prenom" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "nom" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "nomNaissance" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "paysNaissance" character(2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "patrimoineDeclare" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "montantMaxConseille" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "niveauRisque" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "dernierContactAdmin" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "prochainContactDu" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "type" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "titre" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "message" text`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "lu" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ALTER COLUMN "dateNaissance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_992bc479833a12a0f2bfeb29371", ADD CONSTRAINT "FK_992bc479833a12a0f2bfeb29371" FOREIGN KEY ("projetId") REFERENCES "projet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_42a7f009e9f4e9eba6cc349dc4d", ADD CONSTRAINT "FK_42a7f009e9f4e9eba6cc349dc4d" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a721586d3aad982a449d4d6dec4", ADD CONSTRAINT "FK_a721586d3aad982a449d4d6dec4" FOREIGN KEY ("investissementId") REFERENCES "investissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a7552c678d79fc7a7256ee05bf1", ADD CONSTRAINT "FK_a7552c678d79fc7a7256ee05bf1" FOREIGN KEY ("vendeurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_791283f3f6f2453b189909660a6", ADD CONSTRAINT "FK_791283f3f6f2453b189909660a6" FOREIGN KEY ("projet_id") REFERENCES "projet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_2a87c12126792ee18fac7b2e8d8", ADD CONSTRAINT "FK_2a87c12126792ee18fac7b2e8d8" FOREIGN KEY ("utilisateur_id") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a17851bfda0918cbfb0d698490a", ADD CONSTRAINT "FK_a17851bfda0918cbfb0d698490a" FOREIGN KEY ("investissement_id") REFERENCES "investissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_82548d1f8467830e7ec10fcd0d2", ADD CONSTRAINT "FK_82548d1f8467830e7ec10fcd0d2" FOREIGN KEY ("vendeur_id") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_82548d1f8467830e7ec10fcd0d2"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a17851bfda0918cbfb0d698490a"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_2a87c12126792ee18fac7b2e8d8"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_791283f3f6f2453b189909660a6"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a7552c678d79fc7a7256ee05bf1"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a721586d3aad982a449d4d6dec4"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_42a7f009e9f4e9eba6cc349dc4d"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_992bc479833a12a0f2bfeb29371"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ALTER COLUMN "dateNaissance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "createdAt"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "lu"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "message"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "titre"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN IF EXISTS "type"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "prochainContactDu"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "dernierContactAdmin"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "niveauRisque"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "montantMaxConseille"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "patrimoineDeclare"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "paysNaissance"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "nomNaissance"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "nom"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP COLUMN IF EXISTS "prenom"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP COLUMN IF EXISTS "vendeur_id"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP COLUMN IF EXISTS "investissement_id"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP COLUMN IF EXISTS "utilisateur_id"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP COLUMN IF EXISTS "projet_id"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP COLUMN IF EXISTS "nbFractions"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN IF EXISTS "rappelJ1Envoye"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN IF EXISTS "rappelJ7Envoye"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN IF EXISTS "prelevementCSG"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP COLUMN IF EXISTS "prelevementIR"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "annuleLe"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "motifAnnulation"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "echeancierEmprunteur"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "garanties"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "chronologie"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "previsionnel"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "prixFraction"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "nbFractions"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "youtubeUrl"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "longitude"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "latitude"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP COLUMN IF EXISTS "adresseComplete"`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "titre" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "message" text`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "type" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "lu" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "patrimoineDeclare" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "niveauRisque" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "montantMaxConseille" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "dernierContactAdmin" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "prochainContactDu" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "nbFractions" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "rappelJ1Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "rappelJ7Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "prelevementCSG" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "prelevementIR" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "motifAnnulation" text`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "annuleLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "nbFractions" integer`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "chronologie" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "youtubeUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "previsionnel" jsonb`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "garanties" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "latitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "adresseComplete" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "longitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "echeancierEmprunteur" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "prixFraction" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a7552c678d79fc7a7256ee05bf1", ADD CONSTRAINT "FK_a7552c678d79fc7a7256ee05bf1" FOREIGN KEY ("vendeurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a721586d3aad982a449d4d6dec4", ADD CONSTRAINT "FK_a721586d3aad982a449d4d6dec4" FOREIGN KEY ("investissementId") REFERENCES "investissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_42a7f009e9f4e9eba6cc349dc4d", ADD CONSTRAINT "FK_42a7f009e9f4e9eba6cc349dc4d" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_992bc479833a12a0f2bfeb29371", ADD CONSTRAINT "FK_992bc479833a12a0f2bfeb29371" FOREIGN KEY ("projetId") REFERENCES "projet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
