import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1782891038377 implements MigrationInterface {
    name = 'InitSchema1782891038377'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "news" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "titreFr" character varying NOT NULL, "titreEn" character varying, "contenuFr" text NOT NULL, "contenuEn" text, "resumeFr" text, "resumeEn" text, "imageUrl" character varying, "imageUrls" jsonb NOT NULL DEFAULT '[]', "category" character varying, "statut" character varying NOT NULL DEFAULT 'draft', "publishedAt" TIMESTAMP WITH TIME ZONE, "authorId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d09152c44881b7620e12d6df099" UNIQUE ("slug"), CONSTRAINT "PK_39a43dfcb6007180f04aff2357e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "titreFr" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "titreEn" character varying`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "contenuFr" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "contenuEn" text`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "resumeFr" text`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "resumeEn" text`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "imageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "imageUrls" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "category" character varying`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "authorId" integer`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d09152c44881b7620e12d6df09" ON "news" ("slug") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_2bb2261b6ba408164a3daa822c" ON "news" ("statut") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "admin_settings" ("id" character varying NOT NULL DEFAULT 'default', "settings" jsonb NOT NULL DEFAULT '{}', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8eeabc518a2e33306f19fa557cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "admin_settings" ADD COLUMN IF NOT EXISTS "id" character varying NOT NULL DEFAULT 'default'`);
        await queryRunner.query(`ALTER TABLE "admin_settings" ADD COLUMN IF NOT EXISTS "settings" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "admin_settings" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "user_emails" ("userId" SERIAL NOT NULL, "email" character varying NOT NULL, "isVerified" boolean NOT NULL DEFAULT false, "verifiedDate" TIMESTAMP, "user_id" integer, CONSTRAINT "REL_2e88b95787b903d46ab3cc3eb9" UNIQUE ("user_id"), CONSTRAINT "PK_569342223a28f006d9bf897c7c9" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`ALTER TABLE "user_emails" ADD COLUMN IF NOT EXISTS "userId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_emails" ADD COLUMN IF NOT EXISTS "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_emails" ADD COLUMN IF NOT EXISTS "isVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user_emails" ADD COLUMN IF NOT EXISTS "verifiedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_emails" ADD COLUMN IF NOT EXISTS "user_id" integer`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "tfa_methods" ("TFAMethodId" SERIAL NOT NULL, "isActive" boolean NOT NULL, "activatedDate" TIMESTAMP NOT NULL DEFAULT now(), "secretKeyOtp" character varying, "emailOTP" character varying, "phoneNumberOTP" character varying, "type_method" character varying NOT NULL, "user_id" integer, CONSTRAINT "UQ_eb3417033e99e3f89ece05d4f67" UNIQUE ("emailOTP"), CONSTRAINT "PK_cfb2cd00764ac509b752337f41d" PRIMARY KEY ("TFAMethodId"))`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" ADD COLUMN IF NOT EXISTS "TFAMethodId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" ADD COLUMN IF NOT EXISTS "isActive" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" ADD COLUMN IF NOT EXISTS "activatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" ADD COLUMN IF NOT EXISTS "secretKeyOtp" character varying`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" ADD COLUMN IF NOT EXISTS "emailOTP" character varying`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" ADD COLUMN IF NOT EXISTS "phoneNumberOTP" character varying`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" ADD COLUMN IF NOT EXISTS "type_method" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" ADD COLUMN IF NOT EXISTS "user_id" integer`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_bf1c9c94568f6e26329581efa1" ON "tfa_methods" ("type_method") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "users" ("userId" SERIAL NOT NULL, "firstname" character varying, "lastname" character varying, "socialId" character varying, "password" character varying, "role" character varying NOT NULL DEFAULT 'investisseur', "status" character varying NOT NULL DEFAULT 'cree', "cguAccepteesLe" TIMESTAMP, "lastLoginAt" TIMESTAMP, "userType" character varying, "regimeFiscal" character varying NOT NULL DEFAULT 'PFU', "tauxBaremeMarginal" numeric(4,3), "cgpId" integer, "cgpReferralCode" character varying, "pepFlagged" boolean NOT NULL DEFAULT false, "pepNote" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_20f69c0f333d9bd27222a9ceb8b" UNIQUE ("cgpReferralCode"), CONSTRAINT "PK_8bf09ba754322ab9c22a215c919" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "userId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "firstname" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "lastname" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "socialId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "role" character varying NOT NULL DEFAULT 'investisseur'`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "status" character varying NOT NULL DEFAULT 'cree'`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "cguAccepteesLe" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "userType" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "regimeFiscal" character varying NOT NULL DEFAULT 'PFU'`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tauxBaremeMarginal" numeric(4,3)`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "cgpId" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "cgpReferralCode" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "pepFlagged" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "pepNote" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_2025eaefc4e1b443c84f6ca9b2" ON "users" ("socialId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "wallet" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "proprietaireUserId" integer, "projetId" uuid, "spvId" uuid, "fournisseurRef" character varying NOT NULL, "devise" character(3) NOT NULL DEFAULT 'XOF', "solde" numeric(18,2) NOT NULL DEFAULT '0', "statut" character varying NOT NULL DEFAULT 'actif', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bec464dd8d54c39c54fd32e2334" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "proprietaireUserId" integer`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "projetId" uuid`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "spvId" uuid`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "fournisseurRef" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "devise" character(3) NOT NULL DEFAULT 'XOF'`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "solde" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'actif'`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_550c97a35526e250c8f8afac18" ON "wallet" ("proprietaireUserId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "transaction_paiement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletSource" uuid, "wallet_source" uuid, "walletDestination" uuid, "montant" numeric(18,2) NOT NULL, "devise" character(3) NOT NULL DEFAULT 'XOF', "type" character varying NOT NULL, "referenceExterne" character varying, "fournisseur" character varying NOT NULL DEFAULT 'stripe', "fournisseurRef" character varying, "statut" character varying NOT NULL DEFAULT 'initie', "investissementId" uuid, "echeanceId" uuid, "reservationId" uuid, "projetId" uuid, "idempotencyKey" character varying, "fraisPsp" numeric(18,2) NOT NULL DEFAULT '0', "fraisPlateforme" numeric(18,2) NOT NULL DEFAULT '0', "metadata" jsonb, "motifEchec" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_63b76574d65f01b641aaf26c8c1" UNIQUE ("idempotencyKey"), CONSTRAINT "PK_94a63bcd64687185f543d0f4d78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "walletSource" uuid`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "wallet_source" uuid`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "walletDestination" uuid`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "montant" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "devise" character(3) NOT NULL DEFAULT 'XOF'`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "referenceExterne" character varying`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "fournisseur" character varying NOT NULL DEFAULT 'stripe'`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "fournisseurRef" character varying`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'initie'`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "investissementId" uuid`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "echeanceId" uuid`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "reservationId" uuid`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "projetId" uuid`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "idempotencyKey" character varying`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "fraisPsp" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "fraisPlateforme" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "motifEchec" character varying`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_paiement" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_71fb1ec707fcc6668b6bc403a5" ON "transaction_paiement" ("investissementId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "user_preferences" ("userId" integer NOT NULL, "langue" character varying NOT NULL DEFAULT 'fr', "masquerMontants" boolean NOT NULL DEFAULT false, "notifEmail" boolean NOT NULL DEFAULT true, "notifSms" boolean NOT NULL DEFAULT false, "notifMarketing" boolean NOT NULL DEFAULT false, "twoFactorEnabled" boolean NOT NULL DEFAULT false, "preferredCurrency" character varying NOT NULL DEFAULT 'EUR', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b6202d1cacc63a0b9c8dac2abd4" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "langue" character varying NOT NULL DEFAULT 'fr'`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "masquerMontants" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "notifEmail" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "notifSms" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "notifMarketing" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "twoFactorEnabled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "preferredCurrency" character varying NOT NULL DEFAULT 'EUR'`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "signature" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "youSignRequestId" character varying NOT NULL, "youSignSignerId" character varying NOT NULL, "youSignSigningUrl" text, "documentId" uuid NOT NULL, "investmentId" uuid, "ordreId" uuid, "nbFractions" integer, "userId" integer NOT NULL, "statut" character varying NOT NULL DEFAULT 'PENDING', "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "signedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8e62734171afc1d7c9570be27fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "youSignRequestId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "youSignSignerId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "youSignSigningUrl" text`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "documentId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "investmentId" uuid`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "ordreId" uuid`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "nbFractions" integer`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "signedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "signature" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5293f6a508418bd5a81a7a69d4" ON "signature" ("youSignRequestId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_cb4d168533e4128ee6ccf60af5" ON "signature" ("documentId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_217c3bf9b99f0ad7194b16c6a7" ON "signature" ("investmentId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_7fc1cccebe60382b0b15d21487" ON "signature" ("ordreId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_7300eb2628d8e5139f1f109f7e" ON "signature" ("userId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "spv" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "raisonSociale" character varying NOT NULL, "siren" character varying, "forme" character varying, "capitalSocial" numeric(18,2), "siegeAdresse" character varying, "iban" character varying, "dateConstitution" date, "statutsPdfUrl" character varying(1024), "regimeFiscal" character varying NOT NULL DEFAULT 'is', "gestionnaireUserId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_635acd3a59983cf00e2aef91649" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "raisonSociale" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "siren" character varying`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "forme" character varying`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "capitalSocial" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "siegeAdresse" character varying`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "iban" character varying`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "dateConstitution" date`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "statutsPdfUrl" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "regimeFiscal" character varying NOT NULL DEFAULT 'is'`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "gestionnaireUserId" integer`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "spv" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_79174763ed01bf99b8102cc9a5" ON "spv" ("gestionnaireUserId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "projet" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "titre" character varying NOT NULL, "spvId" uuid, "porteurId" integer, "type" character varying NOT NULL, "ville" character varying, "region" character varying, "pays" character(2) NOT NULL DEFAULT 'FR', "adresseComplete" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "youtubeUrl" character varying, "capitalCible" numeric(18,2) NOT NULL, "capitalMinimum" numeric(18,2) NOT NULL, "ticketMinimum" numeric(18,2) NOT NULL DEFAULT '100', "ticketMaximum" numeric(18,2), "triCible" numeric(5,2), "indiceRisque" integer NOT NULL DEFAULT '3', "dureeMois" integer NOT NULL, "instrument" character varying NOT NULL, "statut" character varying NOT NULL DEFAULT 'brouillon', "estPreInvestissable" boolean NOT NULL DEFAULT false, "plafondPreInvestissement" numeric(18,2), "nbFractions" integer, "prixFraction" numeric(18,2), "datePublication" TIMESTAMP WITH TIME ZONE, "dateOuvertureCollecte" TIMESTAMP WITH TIME ZONE, "dateCloturePrevue" TIMESTAMP WITH TIME ZONE, "descriptionMd" text, "avertissementMd" text, "previsionnel" jsonb, "chronologie" jsonb DEFAULT '[]', "garanties" jsonb DEFAULT '[]', "echeancierEmprunteur" jsonb DEFAULT '[]', "modeleEconomique" character varying NOT NULL DEFAULT 'obligataire', "nbUnitesLouables" integer, "motifAnnulation" text, "annuleLe" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4d7d357791e64ef0fe2ec9323df" UNIQUE ("slug"), CONSTRAINT "PK_66b990dd579d8b7e5932661c389" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "titre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "spvId" uuid`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "porteurId" integer`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "ville" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "region" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "pays" character(2) NOT NULL DEFAULT 'FR'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "adresseComplete" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "latitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "longitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "youtubeUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "capitalCible" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "capitalMinimum" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "ticketMinimum" numeric(18,2) NOT NULL DEFAULT '100'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "ticketMaximum" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "triCible" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "indiceRisque" integer NOT NULL DEFAULT '3'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "dureeMois" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "instrument" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'brouillon'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "estPreInvestissable" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "plafondPreInvestissement" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "nbFractions" integer`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "prixFraction" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "datePublication" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "dateOuvertureCollecte" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "dateCloturePrevue" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "descriptionMd" text`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "avertissementMd" text`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "previsionnel" jsonb`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "chronologie" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "garanties" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "echeancierEmprunteur" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "modeleEconomique" character varying NOT NULL DEFAULT 'obligataire'`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "nbUnitesLouables" integer`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "motifAnnulation" text`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "annuleLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projet" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_c0b665a383a6c6126edf800d6e" ON "projet" ("statut") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "echeance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "investissementId" uuid NOT NULL, "numero" integer NOT NULL, "datePrevue" date NOT NULL, "montantCapital" numeric(18,2) NOT NULL DEFAULT '0', "montantInterets" numeric(18,2) NOT NULL DEFAULT '0', "montantTotal" numeric(18,2) NOT NULL DEFAULT '0', "prelevementIR" numeric(14,2) NOT NULL DEFAULT '0', "prelevementCSG" numeric(14,2) NOT NULL DEFAULT '0', "statut" character varying NOT NULL DEFAULT 'a_venir', "payeLe" TIMESTAMP WITH TIME ZONE, "statutChangeLe" TIMESTAMP WITH TIME ZONE, "rappelJ7Envoye" boolean NOT NULL DEFAULT false, "rappelJ1Envoye" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_b916882d3396522c88254529500" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "investissementId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "numero" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "datePrevue" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "montantCapital" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "montantInterets" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "montantTotal" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "prelevementIR" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "prelevementCSG" numeric(14,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'a_venir'`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "payeLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "statutChangeLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "rappelJ7Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "echeance" ADD COLUMN IF NOT EXISTS "rappelJ1Envoye" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_67dc15dbce279c52dfadc5e5f6" ON "echeance" ("investissementId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "investissement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projetId" uuid NOT NULL, "utilisateurId" integer NOT NULL, "montant" numeric(18,2) NOT NULL, "instrument" character varying NOT NULL, "nbTitres" integer, "valeurTitre" numeric(18,2), "statut" character varying NOT NULL DEFAULT 'initie', "delaiRetractationJusquAu" TIMESTAMP WITH TIME ZONE, "bulletinDocId" uuid, "signatureId" uuid, "reservationId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_83cc6569be3e277dc91ec5c697a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "projetId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "utilisateurId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "montant" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "instrument" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "nbTitres" integer`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "valeurTitre" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'initie'`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "delaiRetractationJusquAu" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "bulletinDocId" uuid`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "signatureId" uuid`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "reservationId" uuid`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "investissement" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_992bc479833a12a0f2bfeb2937" ON "investissement" ("projetId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_42a7f009e9f4e9eba6cc349dc4" ON "investissement" ("utilisateurId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "ordre_marche" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "investissementId" uuid NOT NULL, "vendeurId" integer NOT NULL, "acheteurId" integer, "sens" character varying NOT NULL, "nbFractions" integer NOT NULL DEFAULT '0', "montant" numeric(18,2) NOT NULL, "prixUnitaire" numeric(18,2) NOT NULL, "statut" character varying NOT NULL DEFAULT 'en_carnet', "valideJusquAu" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_54870c98e23a2e30530d6ca41c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "investissementId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "vendeurId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "acheteurId" integer`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "sens" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "nbFractions" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "montant" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "prixUnitaire" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'en_carnet'`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "valideJusquAu" date`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_a721586d3aad982a449d4d6dec" ON "ordre_marche" ("investissementId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_a7552c678d79fc7a7256ee05bf" ON "ordre_marche" ("vendeurId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "reservation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projetId" uuid NOT NULL, "utilisateurId" integer NOT NULL, "montantReserve" numeric(18,2) NOT NULL, "rangFile" integer, "statut" character varying NOT NULL DEFAULT 'en_attente', "confirmationJusquAu" TIMESTAMP WITH TIME ZONE, "investissementId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_48b1f9922368359ab88e8bfa525" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "projetId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "utilisateurId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "montantReserve" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "rangFile" integer`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'en_attente'`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "confirmationJusquAu" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "investissementId" uuid`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_46ec0100387ada46815d8ed8f4" ON "reservation" ("projetId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e9750fc27b1127fb9054477a2e" ON "reservation" ("utilisateurId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "sortie_projet" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projetId" uuid NOT NULL, "prixRevente" numeric(18,2) NOT NULL, "dateRevente" date NOT NULL, "plusValueBrute" numeric(18,2) NOT NULL, "statut" character varying NOT NULL DEFAULT 'projetee', "acteVentePdfUrl" character varying(1024), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_36fc9a885e6b3178ea5f00b9e3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "sortie_projet" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "sortie_projet" ADD COLUMN IF NOT EXISTS "projetId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sortie_projet" ADD COLUMN IF NOT EXISTS "prixRevente" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sortie_projet" ADD COLUMN IF NOT EXISTS "dateRevente" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sortie_projet" ADD COLUMN IF NOT EXISTS "plusValueBrute" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sortie_projet" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'projetee'`);
        await queryRunner.query(`ALTER TABLE "sortie_projet" ADD COLUMN IF NOT EXISTS "acteVentePdfUrl" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "sortie_projet" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sortie_projet" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_500ecf5703e6663007efe534d1" ON "sortie_projet" ("projetId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "questionnaire_adequation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "utilisateurId" integer NOT NULL, "workInFinancialSector" boolean NOT NULL DEFAULT false, "moreThan10TransactionsPerQuarter" boolean NOT NULL DEFAULT false, "portfolioOver500k" boolean NOT NULL DEFAULT false, "previousUnlistedInvestments" boolean NOT NULL DEFAULT false, "investmentExperienceOver5Years" boolean NOT NULL DEFAULT false, "financialPatrimonyOver500k" boolean NOT NULL DEFAULT false, "understandsTotalLossRisk" boolean NOT NULL DEFAULT false, "financialSectorBackground" boolean NOT NULL DEFAULT false, "patrimoineNet" numeric(14,2), "revenuAnnuel" numeric(14,2), "budgetAnnuelInvestissement" numeric(14,2), "acceptsSimulatedLoss" boolean NOT NULL DEFAULT false, "resultCategorie" character varying, "resultMontantMaxConseille" numeric(14,2), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_19dc073017897b4303a7fa6559b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "utilisateurId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "workInFinancialSector" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "moreThan10TransactionsPerQuarter" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "portfolioOver500k" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "previousUnlistedInvestments" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "investmentExperienceOver5Years" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "financialPatrimonyOver500k" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "understandsTotalLossRisk" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "financialSectorBackground" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "patrimoineNet" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "revenuAnnuel" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "budgetAnnuelInvestissement" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "acceptsSimulatedLoss" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "resultCategorie" character varying`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "resultMontantMaxConseille" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "questionnaire_adequation" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_ce0fb00c8be314c922f22bb7f0" ON "questionnaire_adequation" ("utilisateurId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "profil_personne_physique" ("utilisateurId" integer NOT NULL, "civilite" character varying, "prenom" character varying NOT NULL, "nom" character varying NOT NULL, "nomNaissance" character varying, "dateNaissance" date, "lieuNaissance" character varying, "paysNaissance" character(2), "nationalite" character(2), "adresseLigne1" character varying, "adresseLigne2" character varying, "codePostal" character varying, "ville" character varying, "pays" character(2), "telephone" character varying, "profession" character varying, "secteurActivite" character varying, "pep" boolean NOT NULL DEFAULT false, "residenceFiscale" character(2), "nif" character varying, "categoriePsfp" character varying NOT NULL DEFAULT 'non_averti', "patrimoineDeclare" numeric(15,2), "montantMaxConseille" numeric(15,2), "niveauRisque" character varying, "dernierContactAdmin" TIMESTAMP WITH TIME ZONE, "prochainContactDu" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_36b8cc065c10a18573332696429" PRIMARY KEY ("utilisateurId"))`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "utilisateurId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "civilite" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "prenom" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "nom" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "nomNaissance" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "dateNaissance" date`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "lieuNaissance" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "paysNaissance" character(2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "nationalite" character(2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "adresseLigne1" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "adresseLigne2" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "codePostal" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "ville" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "pays" character(2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "telephone" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "profession" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "secteurActivite" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "pep" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "residenceFiscale" character(2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "nif" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "categoriePsfp" character varying NOT NULL DEFAULT 'non_averti'`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "patrimoineDeclare" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "montantMaxConseille" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "niveauRisque" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "dernierContactAdmin" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "prochainContactDu" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "profil_personne_morale" ("utilisateurId" integer NOT NULL, "raisonSociale" character varying NOT NULL, "formeJuridique" character varying, "siren" character varying, "rcsVille" character varying, "capitalSocial" numeric(18,2), "siegeAdresse" character varying, "representantId" integer, "secteurActivite" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_121d751c7b6e2a7e868319e3985" PRIMARY KEY ("utilisateurId"))`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "utilisateurId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "raisonSociale" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "formeJuridique" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "siren" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "rcsVille" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "capitalSocial" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "siegeAdresse" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "representantId" integer`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "secteurActivite" character varying`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "kyc" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "utilisateurId" integer NOT NULL, "statut" character varying NOT NULL DEFAULT 'non_demarre', "niveau" character varying NOT NULL DEFAULT 'standard', "scoreRisque" integer, "fournisseur" character varying NOT NULL DEFAULT 'stripe', "fournisseurRef" character varying, "valideJusquAu" date, "motifRefus" character varying, "stripeReportId" character varying, "identiteExtrait" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84ab2e81ea9700d29dda719f3be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "utilisateurId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'non_demarre'`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "niveau" character varying NOT NULL DEFAULT 'standard'`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "scoreRisque" integer`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "fournisseur" character varying NOT NULL DEFAULT 'stripe'`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "fournisseurRef" character varying`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "valideJusquAu" date`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "motifRefus" character varying`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "stripeReportId" character varying`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "identiteExtrait" jsonb`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "kyc" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4c870e84b0faf72b0c4b0b791b" ON "kyc" ("utilisateurId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "beneficiaire_effectif" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profilPMId" integer NOT NULL, "prenom" character varying NOT NULL, "nom" character varying NOT NULL, "dateNaissance" date, "nationalite" character varying, "pourcentageDetention" numeric(5,2) NOT NULL, "pieceIdentiteDocId" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_69f92e7e749bcadb17336676999" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" ADD COLUMN IF NOT EXISTS "profilPMId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" ADD COLUMN IF NOT EXISTS "prenom" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" ADD COLUMN IF NOT EXISTS "nom" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" ADD COLUMN IF NOT EXISTS "dateNaissance" date`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" ADD COLUMN IF NOT EXISTS "nationalite" character varying`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" ADD COLUMN IF NOT EXISTS "pourcentageDetention" numeric(5,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" ADD COLUMN IF NOT EXISTS "pieceIdentiteDocId" character varying`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6262094f06f9167996593f43b0" ON "beneficiaire_effectif" ("profilPMId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "audit_log" ("id" SERIAL NOT NULL, "acteurId" uuid, "role" character varying, "action" character varying NOT NULL, "objetType" character varying, "objetId" uuid, "ip" inet, "userAgent" character varying, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "acteurId" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "role" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "objetType" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "objetId" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "ip" inet`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "userAgent" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "utilisateurId" integer, "canal" character varying, "type" character varying, "titre" character varying, "message" text, "lu" boolean NOT NULL DEFAULT false, "templateCode" character varying, "statut" character varying, "envoyeLe" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "utilisateurId" integer`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "canal" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "type" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "titre" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "message" text`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "lu" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "templateCode" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "statut" character varying`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "envoyeLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "notification" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ac61e666e88b50fd8d8b1a336b" ON "notification" ("utilisateurId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "unite_louable" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projetId" uuid NOT NULL, "reference" character varying(100) NOT NULL, "surfaceM2" numeric(8,2), "loyerMensuelCible" numeric(18,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7a666df70798ba3745e58814f8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "unite_louable" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "unite_louable" ADD COLUMN IF NOT EXISTS "projetId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "unite_louable" ADD COLUMN IF NOT EXISTS "reference" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "unite_louable" ADD COLUMN IF NOT EXISTS "surfaceM2" numeric(8,2)`);
        await queryRunner.query(`ALTER TABLE "unite_louable" ADD COLUMN IF NOT EXISTS "loyerMensuelCible" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "unite_louable" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "unite_louable" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_0bdc0ad10b91a738cbb3a000e5" ON "unite_louable" ("projetId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "loyer_encaisse" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bailId" uuid NOT NULL, "periode" character varying(7) NOT NULL, "montant" numeric(18,2) NOT NULL, "dateEncaissement" date NOT NULL, "preuves" jsonb NOT NULL DEFAULT '[]'::jsonb, "statut" character varying NOT NULL DEFAULT 'declare', "declareParUserId" integer NOT NULL, "valideParUserId" integer, "valideLe" TIMESTAMP WITH TIME ZONE, "motifRejet" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_39b3700b70bd139f1fead1f9f2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "bailId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "periode" character varying(7) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "montant" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "dateEncaissement" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "preuves" jsonb NOT NULL DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'declare'`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "declareParUserId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "valideParUserId" integer`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "valideLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "motifRejet" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "loyer_encaisse" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_709665a924c5e49539badd5800" ON "loyer_encaisse" ("bailId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_01f4bc2bf4180da638875e6d8e" ON "loyer_encaisse" ("bailId", "periode") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "charge" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projetId" uuid NOT NULL, "type" character varying NOT NULL, "description" character varying(500) NOT NULL, "montant" numeric(18,2) NOT NULL, "periode" character varying(7) NOT NULL, "dateOperation" date NOT NULL, "justificatifs" jsonb NOT NULL DEFAULT '[]'::jsonb, "statut" character varying NOT NULL DEFAULT 'declare', "declareParUserId" integer NOT NULL, "valideParUserId" integer, "valideLe" TIMESTAMP WITH TIME ZONE, "motifRejet" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac0381acde3bdffe41ad57cd942" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "projetId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "description" character varying(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "montant" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "periode" character varying(7) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "dateOperation" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "justificatifs" jsonb NOT NULL DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'declare'`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "declareParUserId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "valideParUserId" integer`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "valideLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "motifRejet" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "charge" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d0278ad34a84cea279a00a5872" ON "charge" ("projetId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1e81561ecfaf4b1b6e613952c2" ON "charge" ("projetId", "periode") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "locataire" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nomComplet" character varying(255) NOT NULL, "email" character varying(255), "telephone" character varying(50), "spvId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7ea9ad289d5b7f7243bbe822226" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "locataire" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "locataire" ADD COLUMN IF NOT EXISTS "nomComplet" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locataire" ADD COLUMN IF NOT EXISTS "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "locataire" ADD COLUMN IF NOT EXISTS "telephone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "locataire" ADD COLUMN IF NOT EXISTS "spvId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locataire" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "locataire" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f1fb532e36d546d559fd37f36b" ON "locataire" ("spvId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "bail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "uniteLouableId" uuid NOT NULL, "locataireId" uuid NOT NULL, "loyerMensuel" numeric(18,2) NOT NULL, "dateDebut" date NOT NULL, "dateFin" date, "statut" character varying NOT NULL DEFAULT 'actif', "contratPdfUrl" character varying(1024), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7bbd78d335e5d60120a49ea7208" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "uniteLouableId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "locataireId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "loyerMensuel" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "dateDebut" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "dateFin" date`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'actif'`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "contratPdfUrl" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bail" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_0ed43c83ffbc7cb208e7825103" ON "bail" ("uniteLouableId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_9cc522607864d7ca1417c5fa26" ON "bail" ("locataireId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "document_fiscal" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" integer NOT NULL, "annee" integer NOT NULL, "montantBrut" numeric(18,2) NOT NULL, "montantIR" numeric(18,2) NOT NULL, "montantCSG" numeric(18,2) NOT NULL, "montantNet" numeric(18,2) NOT NULL, "pdfUrl" character varying(1024), "genereeLe" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0c86b785a3f0da84b42136c39be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "annee" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "montantBrut" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "montantIR" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "montantCSG" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "montantNet" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "pdfUrl" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "genereeLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "document_fiscal" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_769e258c0ddd175794cda71c35" ON "document_fiscal" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_a7b50d3fc0e9a40923408d74dd" ON "document_fiscal" ("userId", "annee") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "periode_distribution" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projetId" uuid NOT NULL, "periode" character varying(7) NOT NULL, "totalLoyers" numeric(18,2) NOT NULL DEFAULT '0', "totalCharges" numeric(18,2) NOT NULL DEFAULT '0', "revenuNet" numeric(18,2) NOT NULL DEFAULT '0', "statut" character varying NOT NULL DEFAULT 'calculee', "calculeeLe" TIMESTAMP WITH TIME ZONE NOT NULL, "valideeLe" TIMESTAMP WITH TIME ZONE, "distribueeLe" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d0ff072268a83d4f9c8cb8080f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "projetId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "periode" character varying(7) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "totalLoyers" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "totalCharges" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "revenuNet" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "statut" character varying NOT NULL DEFAULT 'calculee'`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "calculeeLe" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "valideeLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "distribueeLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        // Colonnes de frais portées par PeriodeDistributionFraisColumns1782100000000,
        // qui s'exécute AVANT cette migration et ne trouve donc pas la table sur
        // une base neuve. Reprises ici pour que le rejeu depuis zéro aboutisse au
        // même schéma qu'une base déjà migrée.
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "fraisPlateformeAnnuel" decimal(18,2) NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "fraisGestionLocative" decimal(18,2) NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "periode_distribution" ADD COLUMN IF NOT EXISTS "fraisPlafonnes" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_c3161166f01895d65225021c42" ON "periode_distribution" ("projetId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_e4e1d6b1b1b38d360dd2dc8eec" ON "periode_distribution" ("projetId", "periode") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "document" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "relatedTo" character varying NOT NULL, "userId" integer, "projectId" uuid, "investmentId" uuid, "originalName" character varying NOT NULL, "filename" character varying NOT NULL, "mimeType" character varying NOT NULL, "sizeBytes" integer NOT NULL, "path" character varying NOT NULL, "isPublic" boolean NOT NULL DEFAULT false, "uploadedBy" integer NOT NULL, "ordre" integer, "estPrincipale" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e57d3357f83f3cdc0acffc3d777" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "relatedTo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "userId" integer`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "projectId" uuid`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "investmentId" uuid`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "originalName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "filename" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "mimeType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "sizeBytes" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "path" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "isPublic" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "uploadedBy" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "ordre" integer`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "estPrincipale" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "document" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_7424ddcbdf1e9b067669eb0d3f" ON "document" ("userId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1609339df21e7616eb9ce3dec4" ON "document" ("projectId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_97fa752e93342fdab312a5d1e3" ON "document" ("investmentId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "distribution_part" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "periodeDistributionId" uuid NOT NULL, "investissementId" uuid NOT NULL, "pourcentageDetention" numeric(10,8) NOT NULL, "montantBrut" numeric(18,2) NOT NULL, "prelevementIR" numeric(18,2) NOT NULL DEFAULT '0', "prelevementCSG" numeric(18,2) NOT NULL DEFAULT '0', "montantNet" numeric(18,2) NOT NULL, "payeLe" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_43f512a40e23cf8782f0aa2207b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "periodeDistributionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "investissementId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "pourcentageDetention" numeric(10,8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "montantBrut" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "prelevementIR" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "prelevementCSG" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "montantNet" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "payeLe" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "distribution_part" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f00723d45658b197bb7f0095dd" ON "distribution_part" ("periodeDistributionId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_49729af0ee4b2a855f47e58232" ON "distribution_part" ("investissementId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_5f2745f0b8a6686d23b58205d0" ON "distribution_part" ("periodeDistributionId", "investissementId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "avis" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projetId" uuid NOT NULL, "userId" integer NOT NULL, "note" smallint NOT NULL, "commentaire" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CHK_f868c94c4e6c45794ad3f4a42e" CHECK ("note" >= 1 AND "note" <= 5), CONSTRAINT "PK_a570ebb160501a5b4f8afcde062" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "avis" ADD COLUMN IF NOT EXISTS "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "avis" ADD COLUMN IF NOT EXISTS "projetId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "avis" ADD COLUMN IF NOT EXISTS "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "avis" ADD COLUMN IF NOT EXISTS "note" smallint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "avis" ADD COLUMN IF NOT EXISTS "commentaire" text`);
        await queryRunner.query(`ALTER TABLE "avis" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_25d320ebe8261e744d9b47703f" ON "avis" ("projetId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e0eb07bd223c47b40f1199852e" ON "avis" ("userId") `);
        await queryRunner.query(`ALTER TABLE "user_emails" DROP CONSTRAINT IF EXISTS "FK_2e88b95787b903d46ab3cc3eb91", ADD CONSTRAINT "FK_2e88b95787b903d46ab3cc3eb91" FOREIGN KEY ("user_id") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" DROP CONSTRAINT IF EXISTS "FK_bb0f7b313bc22dcbd060c97d8d4", ADD CONSTRAINT "FK_bb0f7b313bc22dcbd060c97d8d4" FOREIGN KEY ("user_id") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT IF EXISTS "FK_550c97a35526e250c8f8afac188", ADD CONSTRAINT "FK_550c97a35526e250c8f8afac188" FOREIGN KEY ("proprietaireUserId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT IF EXISTS "FK_b6202d1cacc63a0b9c8dac2abd4", ADD CONSTRAINT "FK_b6202d1cacc63a0b9c8dac2abd4" FOREIGN KEY ("userId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projet" DROP CONSTRAINT IF EXISTS "FK_07fcbb0fa2a57a14e6190974176", ADD CONSTRAINT "FK_07fcbb0fa2a57a14e6190974176" FOREIGN KEY ("spvId") REFERENCES "spv"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP CONSTRAINT IF EXISTS "FK_67dc15dbce279c52dfadc5e5f67", ADD CONSTRAINT "FK_67dc15dbce279c52dfadc5e5f67" FOREIGN KEY ("investissementId") REFERENCES "investissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_992bc479833a12a0f2bfeb29371", ADD CONSTRAINT "FK_992bc479833a12a0f2bfeb29371" FOREIGN KEY ("projetId") REFERENCES "projet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_42a7f009e9f4e9eba6cc349dc4d", ADD CONSTRAINT "FK_42a7f009e9f4e9eba6cc349dc4d" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a721586d3aad982a449d4d6dec4", ADD CONSTRAINT "FK_a721586d3aad982a449d4d6dec4" FOREIGN KEY ("investissementId") REFERENCES "investissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a7552c678d79fc7a7256ee05bf1", ADD CONSTRAINT "FK_a7552c678d79fc7a7256ee05bf1" FOREIGN KEY ("vendeurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT IF EXISTS "FK_46ec0100387ada46815d8ed8f4c", ADD CONSTRAINT "FK_46ec0100387ada46815d8ed8f4c" FOREIGN KEY ("projetId") REFERENCES "projet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT IF EXISTS "FK_e9750fc27b1127fb9054477a2e6", ADD CONSTRAINT "FK_e9750fc27b1127fb9054477a2e6" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP CONSTRAINT IF EXISTS "FK_36b8cc065c10a18573332696429", ADD CONSTRAINT "FK_36b8cc065c10a18573332696429" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" DROP CONSTRAINT IF EXISTS "FK_121d751c7b6e2a7e868319e3985", ADD CONSTRAINT "FK_121d751c7b6e2a7e868319e3985" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP CONSTRAINT IF EXISTS "FK_4c870e84b0faf72b0c4b0b791ba", ADD CONSTRAINT "FK_4c870e84b0faf72b0c4b0b791ba" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" DROP CONSTRAINT IF EXISTS "FK_6262094f06f9167996593f43b0f", ADD CONSTRAINT "FK_6262094f06f9167996593f43b0f" FOREIGN KEY ("profilPMId") REFERENCES "profil_personne_morale"("utilisateurId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT IF EXISTS "FK_ac61e666e88b50fd8d8b1a336bd", ADD CONSTRAINT "FK_ac61e666e88b50fd8d8b1a336bd" FOREIGN KEY ("utilisateurId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT IF EXISTS "FK_ac61e666e88b50fd8d8b1a336bd"`);
        await queryRunner.query(`ALTER TABLE "beneficiaire_effectif" DROP CONSTRAINT IF EXISTS "FK_6262094f06f9167996593f43b0f"`);
        await queryRunner.query(`ALTER TABLE "kyc" DROP CONSTRAINT IF EXISTS "FK_4c870e84b0faf72b0c4b0b791ba"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_morale" DROP CONSTRAINT IF EXISTS "FK_121d751c7b6e2a7e868319e3985"`);
        await queryRunner.query(`ALTER TABLE "profil_personne_physique" DROP CONSTRAINT IF EXISTS "FK_36b8cc065c10a18573332696429"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT IF EXISTS "FK_e9750fc27b1127fb9054477a2e6"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT IF EXISTS "FK_46ec0100387ada46815d8ed8f4c"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a7552c678d79fc7a7256ee05bf1"`);
        await queryRunner.query(`ALTER TABLE "ordre_marche" DROP CONSTRAINT IF EXISTS "FK_a721586d3aad982a449d4d6dec4"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_42a7f009e9f4e9eba6cc349dc4d"`);
        await queryRunner.query(`ALTER TABLE "investissement" DROP CONSTRAINT IF EXISTS "FK_992bc479833a12a0f2bfeb29371"`);
        await queryRunner.query(`ALTER TABLE "echeance" DROP CONSTRAINT IF EXISTS "FK_67dc15dbce279c52dfadc5e5f67"`);
        await queryRunner.query(`ALTER TABLE "projet" DROP CONSTRAINT IF EXISTS "FK_07fcbb0fa2a57a14e6190974176"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT IF EXISTS "FK_b6202d1cacc63a0b9c8dac2abd4"`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT IF EXISTS "FK_550c97a35526e250c8f8afac188"`);
        await queryRunner.query(`ALTER TABLE "tfa_methods" DROP CONSTRAINT IF EXISTS "FK_bb0f7b313bc22dcbd060c97d8d4"`);
        await queryRunner.query(`ALTER TABLE "user_emails" DROP CONSTRAINT IF EXISTS "FK_2e88b95787b903d46ab3cc3eb91"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_e0eb07bd223c47b40f1199852e"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_25d320ebe8261e744d9b47703f"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "avis"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_5f2745f0b8a6686d23b58205d0"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_49729af0ee4b2a855f47e58232"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_f00723d45658b197bb7f0095dd"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "distribution_part"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_97fa752e93342fdab312a5d1e3"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_1609339df21e7616eb9ce3dec4"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_7424ddcbdf1e9b067669eb0d3f"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "document"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_e4e1d6b1b1b38d360dd2dc8eec"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_c3161166f01895d65225021c42"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "periode_distribution"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_a7b50d3fc0e9a40923408d74dd"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_769e258c0ddd175794cda71c35"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "document_fiscal"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_9cc522607864d7ca1417c5fa26"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_0ed43c83ffbc7cb208e7825103"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "bail"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_f1fb532e36d546d559fd37f36b"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "locataire"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_1e81561ecfaf4b1b6e613952c2"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_d0278ad34a84cea279a00a5872"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "charge"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_01f4bc2bf4180da638875e6d8e"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_709665a924c5e49539badd5800"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "loyer_encaisse"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_0bdc0ad10b91a738cbb3a000e5"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "unite_louable"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_ac61e666e88b50fd8d8b1a336b"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "notification"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "audit_log"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_6262094f06f9167996593f43b0"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "beneficiaire_effectif"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_4c870e84b0faf72b0c4b0b791b"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "kyc"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "profil_personne_morale"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "profil_personne_physique"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_ce0fb00c8be314c922f22bb7f0"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "questionnaire_adequation"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_500ecf5703e6663007efe534d1"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "sortie_projet"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_e9750fc27b1127fb9054477a2e"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_46ec0100387ada46815d8ed8f4"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "reservation"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_a7552c678d79fc7a7256ee05bf"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_a721586d3aad982a449d4d6dec"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "ordre_marche"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_42a7f009e9f4e9eba6cc349dc4"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_992bc479833a12a0f2bfeb2937"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "investissement"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_67dc15dbce279c52dfadc5e5f6"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "echeance"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_c0b665a383a6c6126edf800d6e"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "projet"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_79174763ed01bf99b8102cc9a5"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "spv"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_7300eb2628d8e5139f1f109f7e"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_7fc1cccebe60382b0b15d21487"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_217c3bf9b99f0ad7194b16c6a7"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_cb4d168533e4128ee6ccf60af5"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_5293f6a508418bd5a81a7a69d4"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "signature"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "user_preferences"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_71fb1ec707fcc6668b6bc403a5"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "transaction_paiement"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_550c97a35526e250c8f8afac18"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "wallet"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_2025eaefc4e1b443c84f6ca9b2"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "users"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_bf1c9c94568f6e26329581efa1"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "tfa_methods"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "user_emails"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "admin_settings"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_2bb2261b6ba408164a3daa822c"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_d09152c44881b7620e12d6df09"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "news"`);
    }

}
