apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Environnement DEV — branche `dev`
namespace: beown-dev

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: beown-backend-config
